routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('User')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('post/{post}', 'PostController@post')->name('post');
    Route::get('post/tag/{tag}', 'HomeController@tagPosts')->name('tagPosts');
    Route::get('post/category/{category}', 'HomeController@categoryPosts')->name('categoryPosts');
    Route::post('get-posts', 'PostController@getPosts');
});

Route::prefix('admin')->group(function () {
    Route::namespace('Admin')->group(function () {
        Route::get('home', 'HomeController@index')->name('admin.home');
        Route::resource('users', 'UsersController');
        Route::resource('post', 'PostController');
        Route::resource('tag', 'TagController');
        Route::resource('category', 'CategoryController');
        Route::resource('role', 'RolesController');
        Route::resource('permissions', 'PermissionsController');
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'Auth\LoginController@login');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\User\Category;
use App\Model\User\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\User\Post;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::all();

        return view('admin.post.show', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        if(Auth::user()->can('posts.create'))
        {
            $tags = Tag::all();
            $categories = Category::all();

            return view('admin.post.post', compact('tags', 'categories'));
        }

        return redirect(route('admin.home'))->withErrors('You don\'t have permissions to create post');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required',
            'subtitle' => 'required',
            'slug' => 'required',
            'body' => 'required',
        ]);

        $post = new Post;
        if ($request->hasFile('image')) {
            $post->image = $request->image->store('public');
        }
        $post->title = $request->title;
        $post->subtitle = $request->subtitle;
        $post->slug = $request->slug;
        $post->body = $request->body;
        if($request->status == 'on') {
            $post->status = 1;
        }
        else {
            $post->status = 0;
        }
        $post->save();
        $post->tags()->sync($request->tags);
        $post->categories()->sync($request->categories);

        return redirect(route('post.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(Auth::user()->can('posts.update'))
        {
            $post = Post::where('id', $id)->first();
            $tags = Tag::all();
            $categories = Category::all();

            return view('admin.post.edit', compact('post', 'categories', 'tags'));
        }

        return redirect(route('admin.home'))->withErrors('You don\'t have permissions to edit post');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'title' => 'required',
            'subtitle' => 'required',
            'slug' => 'required',
            'body' => 'required',
        ]);
        $post = Post::find($id);
        if ($request->hasFile('image')) {
            $post->image = $request->image->store('public');
        }
        $post->title = $request->title;
        $post->subtitle = $request->subtitle;
        $post->slug = $request->slug;
        $post->body = $request->body;
        if($request->status == 'on') {
            $post->status = 1;
        }
        else {
            $post->status = 0;
        }
        $post->save();
        $post->tags()->sync($request->tags);
        $post->categories()->sync($request->categories);

        return redirect(route('post.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(Auth::user()->can('posts.delete'))
        {
            Post::where('id', $id)->delete();

            return redirect()->back();
        }
        return redirect(route('admin.home'))->withErrors('You don\'t have permissions to delete post');
    }
}

app/Http/Controllers/User/PostController.php
<?php

namespace App\Http\Controllers\User;

use App\Model\User\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PostController extends Controller
{
    public function post(Post $post)
    {
        return view('user.post', compact('post'));
    }

    public function getPosts()
    {
        return $posts = Post::where('status', 1)->paginate(2);
    }
}

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.master')

@section('headSection')

    <link rel="stylesheet" href="{{ asset('admin/bower_components/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('user/css/prism.css') }}">

@endsection

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Text Editors
                <small>Advanced form element</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Forms</a></li>
                <li class="active">Editors</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Title</h3>
                        </div>
                        <!-- /.box-header -->
                        @include('includes.errors')
                        <!-- form start -->
                        <form role="form" action="{{ route('post.update', $post->id) }}" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            {{ method_field('PUT') }}
                            <div class="box-body">
                                <div class="col-lg-6">

                                    <div class="form-group">
                                        <label for="title">Post title</label>
                                        <input type="text" class="form-control" id="title" name="title" placeholder="Enter post title" value="{{ $post->title }}">
                                    </div>

                                    <div class="form-group">
                                        <label for="subtitle">Post Subtitle</label>
                                        <input type="text" class="form-control" id="subtitle" name="subtitle" placeholder="Enter post subtitle" value="{{ $post->subtitle }}">
                                    </div>

                                    <div class="form-group">
                                        <label for="slug">Post Slug</label>
                                        <input type="text" class="form-control" id="slug" name="slug" placeholder="Enter slug" value="{{ $post->slug }}">
                                    </div>

                                </div>

                                <div class="col-lg-6">

                                    <div class="pull-right">
                                        <div class="form-group">
                                            <label for="image">File input</label>
                                            <input type="file" id="image" name="image">
                                        </div>
                                    </div>
                                    <div class="pull-left">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="status" @if($post->status == 1) checked @endif> Publish
                                            </label>
                                        </div>
                                    </div>

                                    <br>
                                    <br>

                                    <div class="form-group" style="margin-top:2%;">
                                        <label for="tags">Tags:</label>
                                        <select name="tags[]" id="tags" class="form-control select2 select2-hidden-accessible"
                                                multiple="" data-placeholder="Select a state" style="width:100%;" tabindex="-1"
                                                aria-hidden="true">
                                            @if(isset($tags) && !empty($tags))
                                                @foreach($tags as $tag)
                                                    <option value="{{ $tag->id }}"
                                                    @foreach($post->tags as $postTag)
                                                        @if($postTag->id == $tag->id)
                                                            selected
                                                        @endif
                                                    @endforeach>{{ $tag->name }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label for="categories">Categories:</label>
                                        <select name="categories[]" id="tags" class="form-control select2 select2-hidden-accessible"
                                                multiple="" data-placeholder="Select a state" style="width:100%;" tabindex="-1"
                                                aria-hidden="true">
                                            @if(isset($categories) && !empty($categories))
                                                @foreach($categories as $category)
                                                    <option value="{{ $category->id }}"
                                                        @foreach($post->categories as $postCategory)
                                                            @if($postCategory->id == $category->id)
                                                                selected
                                                            @endif
                                                        @endforeach>{{ $category->name }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>

                                </div>

                                <div class="col-lg-12">

                                    <div class="box">
                                        <div class="box-header">
                                            <h3 class="box-title">Bootstrap WYSIHTML5
                                                <small>Simple and fast</small>
                                            </h3>
                                            <!-- tools box -->
                                            <div class="pull-right box-tools">
                                                <button type="button" class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip"
                                                        title="Collapse">
                                                    <i class="fa fa-minus"></i></button>
                                            </div>
                                            <!-- /. tools -->
                                        </div>
                                        <!-- /.box-header -->
                                        <div class="box-body pad">
                                           <textarea class="textarea" id="editor1" name="body" placeholder="Place some text here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;">{{ $post->body }}</textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a class="btn btn-warning" href="{{ route('post.index') }}">Back</a>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>

@endsection

@section('footerSection')

    <script src="{{ asset('admin/bower_components/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('admin/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('user/js/prism.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
    <script>
        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('editor1')
            //bootstrap WYSIHTML5 - text editor
            $('.textarea').wysihtml5()
        })
    </script>

@endsection

resources/views/admin/post/post.blade.php
@extends('admin.layouts.master')

@section('headSection')

    <link rel="stylesheet" href="{{ asset('admin/bower_components/select2/dist/css/select2.min.css') }}">

@endsection

@section('main-content')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Text Editors
                <small>Advanced form element</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Forms</a></li>
                <li class="active">Editors</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="row">
                <div class="col-md-12">
                    <!-- general form elements -->
                    <div class="box box-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title">Title</h3>
                        </div>
                        <!-- /.box-header -->
                        @include('includes.errors')
                        <!-- form start -->
                        <form role="form" action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
                            {{ csrf_field() }}
                            <div class="box-body">
                                <div class="col-lg-6">

                                    <div class="form-group">
                                        <label for="title">Post title</label>
                                        <input type="text" class="form-control" id="title" name="title" placeholder="Enter post title">
                                    </div>

                                    <div class="form-group">
                                        <label for="subtitle">Post Subtitle</label>
                                        <input type="text" class="form-control" id="subtitle" name="subtitle" placeholder="Enter post subtitle">
                                    </div>

                                    <div class="form-group">
                                        <label for="slug">Post Slug</label>
                                        <input type="text" class="form-control" id="slug" name="slug" placeholder="Enter slug">
                                    </div>

                                </div>

                                <div class="col-lg-6">

                                    <div class="pull-right">
                                        <div class="form-group">
                                            <label for="image">File input</label>
                                            <input type="file" id="image" name="image">
                                        </div>
                                    </div>
                                    <div class="pull-left">
                                        <div class="checkbox">
                                            <label>
                                                <input type="checkbox" name="status"> Publish
                                            </label>
                                        </div>
                                    </div>

                                    <br>
                                    <br>

                                    <div class="form-group" style="margin-top:2%;">
                                        <label for="tags">Tags:</label>
                                        <select name="tags[]" id="tags" class="form-control select2 select2-hidden-accessible"
                                                multiple="" data-placeholder="Select a state" style="width:100%;" tabindex="-1"
                                                aria-hidden="true">
                                            @if(isset($tags) && !empty($tags))
                                                @foreach($tags as $tag)
                                                    <option value="{{ $tag->id }}">{{ $tag->name }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label for="categories">Categories:</label>
                                        <select name="categories[]" id="tags" class="form-control select2 select2-hidden-accessible"
                                                multiple="" data-placeholder="Select a state" style="width:100%;" tabindex="-1"
                                                aria-hidden="true">
                                            @if(isset($categories) && !empty($categories))
                                                @foreach($categories as $category)
                                                    <option value="{{ $category->id }}">{{ $category->name }}</option>
                                                @endforeach
                                            @endif
                                        </select>
                                    </div>

                                </div>

                                <div class="col-lg-12">

                                    <div class="box">
                                        <div class="box-header">
                                            <h3 class="box-title">Bootstrap WYSIHTML5
                                                <small>Simple and fast</small>
                                            </h3>
                                            <!-- tools box -->
                                            <div class="pull-right box-tools">
                                                <button type="button" class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip"
                                                        title="Collapse">
                                                    <i class="fa fa-minus"></i></button>
                                            </div>
                                            <!-- /. tools -->
                                        </div>
                                        <!-- /.box-header -->
                                        <div class="box-body pad">
                                           <textarea class="textarea" id="editor1" name="body" placeholder="Place some text here" style="width: 100%; height: 200px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- /.box-body -->
                            <div class="box-footer">
                                <button type="submit" class="btn btn-primary">Submit</button>
                                <a class="btn btn-warning" href="{{ route('post.index') }}">Back</a>
                            </div>
                        </form>
                    </div>
                    <!-- /.box -->
                </div>
                <!-- /.col-->
            </div>
            <!-- ./row -->
        </section>
        <!-- /.content -->
    </div>

@endsection

@section('footerSection')

    <script src="{{ asset('admin/bower_components/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('admin/ckeditor/ckeditor.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.select2').select2();
        });
    </script>
    <script>
        $(function () {
            // Replace the <textarea id="editor1"> with a CKEditor
            // instance, using default configuration.
            CKEDITOR.replace('editor1')
            //bootstrap WYSIHTML5 - text editor
            $('.textarea').wysihtml5()
        })
    </script>

@endsection

resources/views/admin/post/show.blade.php
@extends('admin.layouts.master')

@section('headSection')

    <link rel="stylesheet" href="{{ asset('admin/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('user/css/prism.css') }}">

@endsection

@section('main-content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Blank page
                <small>it all starts here</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                <li><a href="#">Examples</a></li>
                <li class="active">Blank page</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Posts</h3>
                    @can('posts.create', Auth::user())
                        <a class="col-lg-offset-5 btn btn-success" href="{{ route('post.create') }}">Add new post</a>
                    @endcan
                    <div class="box-tools pull-right">
                        <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip"
                                title="Collapse">
                            <i class="fa fa-minus"></i></button>
                        <button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="Remove">
                            <i class="fa fa-times"></i></button>
                    </div>
                </div>
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Post title</th>
                            <th>Post subtitle</th>
                            <th>Post slug</th>
                            <th>Post body</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($posts as $post)
                            <tr>
                                <td>{{ $post->id }}</td>
                                <td>{{ $post->title }}</td>
                                <td>{{ $post->subtitle }}</td>
                                <td>{{ $post->slug }}</td>
                                <td>{{ $post->body }}</td>
                                <td>
                                    @can('posts.update', Auth::user())
                                        <a href="{{ route('post.edit', $post->id) }}"><span class="glyphicon glyphicon-edit"></span></a>
                                    @endcan
                                </td>
                                <td>
                                    @can('posts.delete', Auth::user())
                                        <form id="delete-form-{{ $post->id }}" method="post" action="{{ route('post.destroy', $post->id) }}">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                        </form>
                                        <a href="{{ route('post.index') }}" onclick="
                                                if(confirm('Are you sure, You want to delete this category?')) {
                                                event.preventDefault();
                                                document.getElementById('delete-form-{{ $post->id }}').submit();
                                                } else {
                                                event.preventDefault();
                                                }"
                                           }>
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </a>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    </table>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    Footer
                </div>
                <!-- /.box-footer-->
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

@section('footerSection')
    <script src="{{ asset('admin/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('admin/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

    <script src="{{ asset('admin/bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('admin/bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
    <script src="{{ asset('admin/bower_components/fastclick/lib/fastclick.js') }}"></script>
    <script src="{{ asset('admin/dist/js/adminlte.min.js') }}"></script>
    <script src="{{ asset('user/js/prism.js') }}"></script>

@endsection