routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::namespace('User')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('post/{post}', 'PostController@post')->name('post');
    Route::get('post/tag/{tag}', 'HomeController@tagPosts')->name('tagPosts');
    Route::get('post/category/{category}', 'HomeController@categoryPosts')->name('categoryPosts');
    Route::post('get-posts', 'PostController@getPosts');
});

Route::prefix('admin')->group(function () {
    Route::namespace('Admin')->group(function () {
        Route::get('home', 'HomeController@index')->name('admin.home');
        Route::resource('users', 'UsersController');
        Route::resource('post', 'PostController');
        Route::resource('tag', 'TagController');
        Route::resource('category', 'CategoryController');
        Route::resource('role', 'RolesController');
        Route::resource('permissions', 'PermissionsController');
        Route::get('login', 'Auth\LoginController@showLoginForm')->name('admin.login');
        Route::post('login', 'Auth\LoginController@login');
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/admin/layouts/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
    <script src="{{ asset('admin/bower_components/jquery/dist/jquery.min.js') }}"></script>

    @section('footerSection')
        @show

</footer>

resources/views/admin/layouts/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>AdminLTE 2 | Dashboard</title>
<!-- Tell the browser to be responsive to screen width -->
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap/dist/css/bootstrap.min.css') }}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/font-awesome/css/font-awesome.min.css') }}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/Ionicons/css/ionicons.min.css') }}">
<!-- Theme style -->
<link rel="stylesheet" href="{{ asset('admin/dist/css/AdminLTE.min.css') }}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
     folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{ asset('admin/dist/css/skins/_all-skins.min.css') }}">
<!-- Morris chart -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/morris.js/morris.css') }}">
<!-- jvectormap -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/jvectormap/jquery-jvectormap.css') }}">
<!-- Date Picker -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css') }}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{{ asset('admin/bower_components/bootstrap-daterangepicker/daterangepicker.css') }}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{ asset('admin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

@section('headSection')
    @show

resources/views/admin/layouts/master.blade.php
<!doctype html>
<html lang="en">
<head>

    @include('admin.layouts.head')

</head>
<body>

    @include('admin.layouts.header')

    @include('admin.layouts.sidebar')

    @section('main-content')

        @show

    @include('admin.layouts.footer')

</body>
</html>

resources/views/admin/layouts/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('admin/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- search form -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
            </div>
        </form>
        <!-- /.search form -->
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=""><a href="{{ route('post.index') }}"><i class="fa fa-circle-o"></i> Posts </a></li>
                    <li><a href="{{ route('category.index') }}"><i class="fa fa-circle-o"></i> Categories </a></li>
                    <li><a href="{{ route('tag.index') }}"><i class="fa fa-circle-o"></i> Tags </a></li>
                    <li><a href="{{ route('users.index') }}"><i class="fa fa-circle-o"></i> Users </a></li>
                    <li><a href="{{ route('role.index') }}"><i class="fa fa-circle-o"></i> Roles </a></li>
                    <li><a href="{{ route('permissions.index') }}"><i class="fa fa-circle-o"></i> Permissions </a></li>
                </ul>
            </li>
            <li class="active treeview">
                <a href="#">
                    <i class="fa fa-dashboard"></i> <span>Creation board</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class=""><a href="{{ route('post.create') }}"><i class="fa fa-circle-o"></i> Posts </a></li>
                    <li><a href="{{ route('category.create') }}"><i class="fa fa-circle-o"></i> Categories </a></li>
                    <li><a href="{{ route('tag.create') }}"><i class="fa fa-circle-o"></i> Tags </a></li>
                    <li><a href="{{ route('users.create')}}"><i class="fa fa-circle-o"></i> Users </a></li>
                    <li><a href="{{ route('role.create')}}"><i class="fa fa-circle-o"></i> Roles </a></li>
                    <li><a href="{{ route('permissions.create')}}"><i class="fa fa-circle-o"></i> Permissions </a></li>
                </ul>
            </li>
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>